{
    "name": "MPO - Travel Fleet",
    "version": "16.0.2.0.0",
    "author": "Port Cities",
    "website": "https://www.portcities.net",
    "sequence": 1,
    "category": "Human Resources/Fleet",
    "summary": "Customization Fleet module",
    "depends": ["fleet", "sale"],
    "data": [
        "data/fleet_data.xml",
        "data/ir_sequence.xml",
        "views/fleet_views.xml",
        "views/sale_order_views.xml",
        "views/account_move_views.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
    "license": "AGPL-3",
}
