{
    "name": "MPO - Transport Request",
    "version": "16.0.2.0.0",
    "author": "Port Cities",
    "website": "https://www.portcities.net",
    "sequence": 1,
    "category": "Purchase",
    "summary": "Transport Request",
    "depends": [
        "mpo_sir",
        "bi_convert_sales_from_purchase",
        "base_address_extended"],
    "data": [
        "data/ir_sequence.xml",
        "security/transport_security.xml",
        "security/ir.model.access.csv",
        "views/unit_type_views.xml",
        "views/custom_tariff_route_views.xml",
        "views/customer_rate_service_views.xml",
        "views/custody_type_views.xml",
        "views/transport_request_views.xml",
        "views/load_order_views.xml",
        "views/res_partner_views.xml",
        "views/menuitem.xml",
        "reports/paperformat.xml",
        "reports/report_transport_request.xml",
        "reports/report_load_order.xml",
        "views/purchase_order_views.xml",
        "views/sale_order_views.xml",
        "wizard/sale_order_wizard_view.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
    "license": "AGPL-3",
}
